import * as argon2 from 'argon2';
import { injectable } from 'inversify';

import { IUser } from '../model/user-model';


@injectable()
export class UserService {

    public generateUsername({
        first_name, 
        last_name, 
        domain='email.com'
    }: {
        first_name: string;
        last_name: string;
        domain?: string;
    }) {

        const firstThreeLettersFname = first_name.substring(0, 3).toLowerCase();
        const finalUsername = `${firstThreeLettersFname}${last_name}@${domain}`;
        return finalUsername;
    }


    public async generateUserEntry({
        userData
    }: {
        userData: IUser;
    }): Promise<IUser> {

        const newUserData = { ...userData };
        const passwordHashed = await argon2.hash(newUserData.password);
        const usernameAutoGenerated = this.generateUsername({
            first_name: newUserData.first_name,
            last_name: newUserData.last_name,
        });
        newUserData.password = passwordHashed;
        newUserData.username = usernameAutoGenerated;

        return newUserData as IUser;
    }
}